# Generated by Django 4.2.1 on 2023-06-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mallbilling', '0005_alter_admin_admin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='employee_id',
        ),
    ]
