# Generated by Django 4.2.1 on 2023-07-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallbilling', '0006_rename_email_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
