# Generated by Django 4.2.1 on 2023-06-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallbilling', '0004_remove_employee_employee_id_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
